In [ ]:
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1r24EGVevDCKLImoBAOmG2rvJ4Ip1K-Xv')

In [ ]:
import torch
# torch module contains all the functionalities of pytorch
# PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, 
# or any n-dimensional array. Let's create a tensor with a single number

In [ ]:
# Number
t1 = torch.tensor(4.)    # 4. representing a floating point number.
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
# lets create more complex tensors
t2 = torch.tensor([1.,2,3,4])
t2
# all the elements of a tensor should be of same type 

In [ ]:
t2.dtype

torch.float32

In [ ]:
t3 = torch.tensor( [[5.,6.],
                    [7.,8.],
                    [4.,3.]])
t3.dtype

torch.float32

In [ ]:
t4 = torch.tensor([
        [[1.,3.,4.,76.],
         [5.,5.,6.,2.],
         [5.,6.,8.,23.]],
                                  # three- dime tensor
         [[23.,45.,65.,3.],
         [23.,11.,33.,2.],
        [45.,34.,223.,243.]]
        ]) 

In [ ]:
t4

tensor([[[  1.,   3.,   4.,  76.],
         [  5.,   5.,   6.,   2.],
         [  5.,   6.,   8.,  23.]],

        [[ 23.,  45.,  65.,   3.],
         [ 23.,  11.,  33.,   2.],
         [ 45.,  34., 223., 243.]]])

In [ ]:
print(t1)
t1.shape 

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[5., 6.],
        [7., 8.],
        [4., 3.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[  1.,   3.,   4.,  76.],
         [  5.,   5.,   6.,   2.],
         [  5.,   6.,   8.,  23.]],

        [[ 23.,  45.,  65.,   3.],
         [ 23.,  11.,  33.,   2.],
         [ 45.,  34., 223., 243.]]])


torch.Size([2, 3, 4])

In [ ]:
# tensor should have definite shape
# and all the elements must be of same datatype

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w * x + b 
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward()     # computing gradients
print('dy/dx:', x.grad)  # none because we do not mentioned the requires grad parameter
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


The grad is short for gradient, which is another term for derivative. The gradient is primarily used while dealing with vectors and matrices.

Now , apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples






In [ ]:
# create a tensor with a fixed value for every element 
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
# concatenate two tensors with compatible shapes
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 4.,  3.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
# computing the sin of each element 
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [-0.7568,  0.1411],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
# changing the shape of tensor
t9 = t8.reshape(4,3,1)
t9

tensor([[[-0.9589],
         [-0.2794],
         [ 0.6570]],

        [[ 0.9894],
         [-0.7568],
         [ 0.1411]],

        [[-0.9165],
         [-0.9165],
         [-0.9165]],

        [[-0.9165],
         [-0.9165],
         [-0.9165]]])

You can learn more about tensor operations here: https://pytorch.org/docs/stable/torch.html . Experiment with some more tensor functions and operations using the empty cells below.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]]) 
x

array([[1, 2],
       [3, 4]])

In [ ]:
# lets convert numpy array into torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [ ]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [ ]:
# lets convert torch tensor to numpy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

Why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:
1. Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

## Summary and Further Reading

Try out this assignment to learn more about tensor operations in PyTorch: https://jovian.ai/aakashns/01-tensor-operations


This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy


You can learn more about PyTorch tensors here: https://pytorch.org/docs/stable/tensors.html. 


The material in this series is inspired by:

* [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi 
* [FastAI development notebooks](https://github.com/fastai/fastai_docs/tree/master/dev_nb) by Jeremy Howard. 

With this, we complete our discussion of tensors and gradients in PyTorch, and we're ready to move on to the next topic: [Gradient Descent & Linear Regression](https://jovian.ai/aakashns/02-linear-regression).

Questions for Review
Try answering the following questions to test your understanding of the topics covered in this notebook:

1. What is PyTorch?
2. What is a Jupyter notebook?
3. What is Google Colab?
4. How do you install PyTorch?
5. How do you import the torch module?
6. What is a vector? Give an example.
7. What is a matrix? Give an example.
8. What is a tensor?
9. How do you create a PyTorch tensor?Illustrate with examples.
10. What is the difference between a tensor and a vector or a matrix?
11. Is every tensor a matrix?
12. Is every matrix a tensor?
13. What does the dtype property of a tensor represent?
14. Is it possible to create a tensor with elements of different data types?
15. How do you inspect the number of dimensions of a tensor and the length along each dimension?
16. Is it possible to create a tensor with the values [[1, 2, 3], [4, 5]]? Why or why not?
17. How do you perform arithmetic operations on tensors? Illustrate with examples?
18. What happens if you specify requires_grad=True while creating a tensor? Illustrate with an example.
19. What is autograd in PyTorch? How is it useful?
20. What happens when you invoke the backward method of a tensor?

21. How do you check the derivates of a result tensor w.r.t. the tensors used to compute its value?

22. Give some examples of functions available in the torch module for creating tensors.

23. Give some examples of functions available in the torch module for performing mathematical operations on tensors.

24. Where can you find the list of tensor operations available in PyTorch?

25. What is Numpy?
26. How do you create a Numpy array?

27. How do you create a PyTorch tensor using a Numpy array?

28. How do you create a Numpy array using a PyTorch tensor?

29. Why is interoperability between PyTorch and Numpy important?

30. What is the purpose of a library like PyTorch if Numpy already provides data structures and utilities to with multi-dimensional numeric data?