In [22]:
import torch
import numpy as np

## Tensor Creation

In [23]:
# randomly initializing the torch tensor 
torch.Tensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.rand(2,3) # uniform random

tensor([[0.0391, 0.0728, 0.5779],
        [0.7588, 0.9120, 0.5890]])

In [15]:
torch.randn(2,3) # random normal

tensor([[-1.1517,  0.3821, -0.9215],
        [-0.6745,  0.2094,  0.4503]])

In [16]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(2,3)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [19]:
torch.ones(2,3).fill_(4)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [21]:
torch.Tensor([[1,4,2],[45,2,3]])

tensor([[ 1.,  4.,  2.],
        [45.,  2.,  3.]])

In [24]:
npy_ar = np.random.rand(2,3)
npy_ar

array([[0.13502553, 0.60729336, 0.41503516],
       [0.80660804, 0.5362513 , 0.25335758]])

In [25]:
torch.from_numpy(npy_ar)

tensor([[0.1350, 0.6073, 0.4150],
        [0.8066, 0.5363, 0.2534]], dtype=torch.float64)

In [27]:
x = torch.FloatTensor([[1,2,45],[5,2,6]])
x

tensor([[ 1.,  2., 45.],
        [ 5.,  2.,  6.]])

In [28]:
x.long()

tensor([[ 1,  2, 45],
        [ 5,  2,  6]])

In [36]:
x  = torch.tensor([[1,2,4],[58,39,40]],dtype = torch.int64)
x

tensor([[ 1,  2,  4],
        [58, 39, 40]])

In [37]:
x.float() 

tensor([[ 1.,  2.,  4.],
        [58., 39., 40.]])

In [38]:
x.shape

torch.Size([2, 3])

In [40]:
x.size()

torch.Size([2, 3])

## Tensor Operations

In [41]:
x = torch.randn(2,3)
print(x)
y = torch.add(x,x)
print(y)

tensor([[ 0.2878,  1.8393,  0.0892],
        [ 0.1824, -0.3536,  0.0946]])
tensor([[ 0.5756,  3.6786,  0.1784],
        [ 0.3648, -0.7073,  0.1893]])


In [42]:
x+x

tensor([[ 0.5756,  3.6786,  0.1784],
        [ 0.3648, -0.7073,  0.1893]])

In [51]:
x = torch.arange(6)
x[1] = 129
x

tensor([  0, 129,   2,   3,   4,   5])

In [53]:
x = x.view(2,3)
x

tensor([[  0, 129,   2],
        [  3,   4,   5]])

In [55]:
torch.sum(x,dim=0) # rowwise addition 

tensor([  3, 133,   7])

In [57]:
torch.sum(x,dim=1) # columnwise addition 

tensor([131,  12])

In [62]:
torch.transpose(x,0,1)

tensor([[  0,   3],
        [129,   4],
        [  2,   5]])

In [69]:
x = torch.arange(12).view(4,3)
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [82]:
x[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]])

In [76]:
x[1,2]

tensor(5)

In [80]:
indices = torch.LongTensor([0,2])
print(indices)
torch.index_select(x,dim = 0,index = indices)

tensor([0, 2])


tensor([[0, 1, 2],
        [6, 7, 8]])

In [81]:
torch.index_select(x,dim = 0,index = indices)

tensor([[0, 1, 2],
        [6, 7, 8]])

In [84]:
indices = torch.LongTensor([0,0])
print(indices)
torch.index_select(x,dim = 0,index = indices)

tensor([0, 0])


tensor([[0, 1, 2],
        [0, 1, 2]])

In [85]:
torch.index_select(x,dim = 1,index = indices)

tensor([[0, 0],
        [3, 3],
        [6, 6],
        [9, 9]])

In [86]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
print(row_indices)
print(col_indices)
x[row_indices,col_indices]

tensor([0, 1])
tensor([0, 1])


tensor([0, 4])

In [89]:
# concatenation 
x = torch.arange(6).view(2,3)
print(x)
y = torch.cat([x,x],dim = 0)
print(y)
z = torch.cat([x,x],dim = 1)
print(z)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [96]:
stacked = torch.stack([x,x])
print(stacked)
print(stacked.dim())
print(stacked.size())

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])
3
torch.Size([2, 2, 3])


In [108]:
x1 = torch.arange(6).view(2,3).long()
x2 = torch.ones(3,2).long()
print(x1)
print(x2)
x2[:,1] +=1
print(x2)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[1, 1],
        [1, 1],
        [1, 1]])
tensor([[1, 2],
        [1, 2],
        [1, 2]])


In [109]:
torch.mm(x1,x2)

tensor([[ 3,  6],
        [12, 24]])

## Gradient BookKeeping 

In [112]:
x = torch.ones(2,2,requires_grad = True)
print(x)
print(x.grad is None)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [123]:
x = torch.ones(2,2,requires_grad = True)
y = (x+2)*(x+5)+3
print(y)

tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


In [132]:
z = y.mean()
print(z)

tensor(21., grad_fn=<MeanBackward0>)


In [128]:
z.backward()

In [129]:
x.grad

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

In [130]:
y.grad

In [133]:
z.grad