In [1]:
import torch

In [2]:
a = torch.tensor([5.],requires_grad = True)
b = torch.tensor([6.],requires_grad = True) 

In [3]:
y = a**3-b**2   # 3a**2+2b 
y 

tensor([89.], grad_fn=<SubBackward0>)

In [4]:
#dy/da  = 3a**2  ==> 3*25 ==> 75 
# dy/db = -2a   ==> -2*6 ==> -12 

In [7]:
a.grad,b.grad

(None, None)

In [8]:
y.backward()

In [9]:
a.grad

tensor([75.])

In [10]:
b.grad

tensor([-12.])

In [11]:
W = torch.randn(10,1,requires_grad = True)
b = torch.randn(1,requires_grad = True)

In [12]:
W

tensor([[-0.4432],
        [-2.3795],
        [-1.2929],
        [ 1.1638],
        [ 0.5061],
        [-0.9747],
        [-0.4549],
        [ 0.9977],
        [ 1.1704],
        [-2.7091]], requires_grad=True)

In [13]:
b

tensor([1.7405], requires_grad=True)

In [17]:
x = torch.rand(1,10)
x  # one sample with many feaures (10)

tensor([[0.1212, 0.2198, 0.9216, 0.0313, 0.4312, 0.5887, 0.0465, 0.5940, 0.4852,
         0.4910]])

In [18]:
output = torch.matmul(x,W)+b

In [19]:
output

tensor([[-0.5378]], grad_fn=<AddBackward0>)

In [20]:
loss = 1-output

In [21]:
loss

tensor([[1.5378]], grad_fn=<RsubBackward1>)

In [22]:
loss.backward()

In [23]:
W.grad

tensor([[-0.1212],
        [-0.2198],
        [-0.9216],
        [-0.0313],
        [-0.4312],
        [-0.5887],
        [-0.0465],
        [-0.5940],
        [-0.4852],
        [-0.4910]])

In [24]:
b.grad

tensor([-1.])

In [29]:
# here i dont want to keep the gradient but just the update 
learning_rate = 0.01
with torch.no_grad():
    W = W-learning_rate*W.grad.data

In [30]:
W

tensor([[-0.4420],
        [-2.3773],
        [-1.2837],
        [ 1.1641],
        [ 0.5105],
        [-0.9688],
        [-0.4545],
        [ 1.0037],
        [ 1.1752],
        [-2.7042]])